### ISSUE TITLE
Extension key "typo3_debugbar" not loaded

### ISSUE THREAD

**Issue by robert-heinig** [Konafets/typo3_debugbar#1]
Typo3DebugBar::EXTENSION_KEY is set to "typo3_debugbar", while the actual extension key is "typo_debugbar", which causes an extension key not loaded exception.
I installed the extension with composer and the extenion directory within typo3onf/ext is "typo_debugbar", in PackageStates.php the package was also registered with "typo_debugbar".

**Comment by dhuf** [comment]
Could it be https://github.com/Konafets/typo3_debugbar/blob/develop/composer.json#L19

**Comment by beathorst** [comment]
same problem

**Comment by peterkraume** [comment]
same problem here
