### ISSUE TITLE
PHP Error due to missing class can not load debug bar in 1.2.0

### ISSUE THREAD

**Issue by angeloprevitali** [Konafets/typo3_debugbar#12]
As already wrote in old issue the EXT 1.2.0 cannot be loaded due to the same error leading in as described in https://github.com/Konafets/typo3_debugbar/issues/1.

Can you fix this?

Thanks.

**Comment by paravista** [comment]
Same thing here: Class 'DebugBar\DataCollector\DataCollector' not found in ext\typo3_debugbar\Classes\DataCollectors\BaseCollector.php on line 14 

It is working like a charm in a composer based installation, but not in a classic symlink install. Both have 8.7.10 and PHP 7.0 (tried 7.1 as well). I assume failed autoloading or a missing dependency.

Any help appreciated. Big thanks for the author as it is a please to work with the debug bar!
