### ISSUE TITLE
Mismatch between dependencies defined in composer.json and ext_emconf.php

### ISSUE THREAD

**Issue by nostadt** [Konafets/typo3_debugbar#14]
According to the ext_emconf.php T3 7.6.0-8.7.99 is required. However, in the composer.json it depends on T3>=8.7.0

https://github.com/Konafets/typo3_debugbar/blob/master/composer.json#L15
https://github.com/Konafets/typo3_debugbar/blob/master/ext_emconf.php#L16

Which dependency is the correct one? Would be great if it's corrected soon.

**Comment by Konafets** [comment]
Thanks for pointing this out. I set the TYPO3 version to 8.7.0 in `ext_emconf.php` in version 1.3.0. This is due I did not test it in any other version yet.
