### ISSUE TITLE
TYPO3 v9 support

### ISSUE THREAD

**Issue by samowitsch** [Konafets/typo3_debugbar#45]
### Type of TYPO3 installation 

- [x] Composer
- [x] Classic

### Expected behavior
Support for T3v9LTS would be great!

**Comment by Konafets** [comment]
Hi,

I did not look into v9.0 yet but I know that the core team wanted to include the functionality of this extension into 9.0 and when I look at these screenshots (go to section "Admin Panel", it seems they did it.

https://typo3.org/article/typo3-v9-lts-youre-the-one-that-i-want/ 

Please let me know if the new admin panel already covers this functionality.

**Comment by samowitsch** [comment]
Yes you are right v9 with its rewritten adminpanel has a similar functionality. But i don't have compared both in detail. I will close this. Regards.
