### ISSUE TITLE
Shipped jQuery 1.12.4 breaks my own jQuery

### ISSUE THREAD

**Issue by peterkraume** [Konafets/typo3_debugbar#5]
EXT:typo3_debugbar ships with `Resources/Public/JavaScript/debugbar.js` which includes jQuery 1.12.4. This breaks the jQuery that I've included in my theme extension.

Do you have any idea how to approach this problem. Maybe you can add a possibility to make the jQuery inclusion optional?

**Comment by Konafets** [comment]
Debugbar.js comes from the upstream lib. Need to look into it.

**Comment by Konafets** [comment]
@peterkraume Can you check latest version of develop branch? Let me know if the issue is fixed.

**Comment by Konafets** [comment]
Fixed in 8819824de358415e1d2c0eea11b0c7c34cec4e0c

**Comment by peterkraume** [comment]
Sorry, wasn't able to test earlier. I've now tested version 1.2.0 and it seems to run smoothly. Thx for the solution.
